apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend-ns
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: image-test
  newName: image-test
  newTag: firstBuild
